### ISSUE TITLE
I only get a partial connect - first line

### ISSUE THREAD

**Issue by tuzen** [Grahnz/TwitchIRC-Unity#1]
Unity 5.3.4 - I can connect, then I only receive one line:
:tmi.twitch.tv 001 userxasdf :Welcome, GLHF!

I'm missing all further traffic - is this still working for anybody else?

thx!!

**Comment by Grahnz** [comment]
I haven't used this project in a couple of months. How did you encounter this issue? I'm guessing Unity 5.3.4 has some update that conflicts or twitch updated their end. I will look into it if i get time, cheers.

**Comment by tuzen** [comment]
I have it working - it was completely user error in the end. =)

**Comment by Grahnz** [comment]
Alright :) good luck with ur game/app
